### ISSUE TITLE
User table

### ISSUE THREAD

**Issue by MandyMoo3677** [5CS024-Team1/database#5]
Can you confirm if you can create a user table with permissions? - Sorry Lucy - this completely skipped my mind and i am unsure where this sits.

**Comment by LuceMook87** [comment]
Permissions in what way?
Patients won't be tracking or requesting items. So anyone that uses the product will be a member of staff...

**Comment by MandyMoo3677** [comment]
I think that the user permissions allowing different access will require logins.  I dont think it would be attached to the ERD you have.  Just a simple Name, where from, title, password and user level 1? I have spoken with Software Devs and i think my understanding was that a table would be required because that is what security Consultant wants.

**Comment by LuceMook87** [comment]
If its a table, it needs to be in the ERD.
I'm not working today but I will add it in tomorrow :) might change the ID table that stems off the person table on a 1:1 relationship into a user table. Using person table as a link entity means all the information can be pulled through to a user table, I think.

**Comment by LuceMook87** [comment]
Updated ERD with User table , uploading final design shortly & DDL scripts v2 to basecamp & here on Github
