### ISSUE TITLE
Handling account type

### ISSUE THREAD

**Issue by ghost** [5CS024-Team1/database#7]
Just an issue i'm having with handling the users account type (admin/regular etc) and how we are going to go about handling it. We could do a Boolean attribute called admin that simply applies true or false to if the user account is an admin. 

We could also do something with triggers.

Any help would be great just so I can figure out how to handle it on the web app

**Comment by LuceMook87** [comment]
Triggers may be the best option. Effectively a conditional statement to keep data secure and only accessible by  specified accounts :)

**Comment by LuceMook87** [comment]
Because the data type is Varchar could be as simple as assigning staff users with an ID of NHS####, then implementing a trigger of if ID contains NHS then staff privaledges

**Comment by ghost** [comment]
Yeah that clears up my issue, so we'd do something like NHS#### for regular accounts and NHSA#### for admin controls?

**Comment by LuceMook87** [comment]
Yep something along those lines :)

**Comment by LuceMook87** [comment]
I think this issue has been handled now with the changing of data types and the other issues raised with User table and ID tables
