### ISSUE TITLE
User table ID

### ISSUE THREAD

**Issue by ghost** [5CS024-Team1/database#8]
Hi Luce,  just wondering if a change could be made to the user table to either replace username with staffID or for staffID to be added as a foreign key. This is just so when using the login we can see what the users account is when they log in (regular staff or admin). #5

**Comment by LuceMook87** [comment]
added and updated .sql file :)
If you dont want to reload the whole thing, if you open the file in notepad the constraint for the FK is at the bottom but the table will need the column adding so it may just be easier to import the file and run it as a whole.
